<?xml version="1.0" encoding="utf-8"?>
<metadata xmlns:r="http://dev.rcware.eu/serialization/references" xmlns="http://dev.rcware.eu/shark-ide-2">
  <values>
    <m type="library.metadata.call" fullName="$main$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_uart_config_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ai_mode_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ao_mode_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_pwm_cycle_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_pwm_prescale_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_toggle_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_toggle_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_toggle_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_toggle_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_polarity_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_polarity_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_polarity_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_polarity_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_enable_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_enable_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_enable_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ds_enable_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_debounce_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_debounce_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_debounce_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_debounce_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_mwd_timeout_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_uled_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_uled_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_uled_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_uled_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_pwm_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_pwm_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_pwm_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_pwm_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_mwd_enable_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ao_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_do_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_do_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_do_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_do_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_mwd1_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_mwd1_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_mwd1_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_aio_v_offset_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_aio_v_dev_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ai_a_offset_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ai_a_dev_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ai_v_offset_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ai_v_dev_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ao_a_offset_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ao_a_dev_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ao_v_offset_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ao_v_dev_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_vref_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_boardserial_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_hwversion_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_version_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig1_rd_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig1_rd_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig1_rd_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.01_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.01_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.01_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.01_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.01_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.01_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ow_off_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_owoff1_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_owoff1_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_owoff1_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.04_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.04_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.04_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_psc1_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_psc1_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_psc1_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.01_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.01_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.01_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.03_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.03_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.03_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.02_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.02_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dsp1.02_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.04_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.04_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.04_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.01_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.01_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.01_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.03_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.03_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.03_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.03_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.03_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.03_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.01_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.01_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.01_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.02_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.02_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.02_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.03_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.03_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_debounce1.03_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_cnt_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_cnt_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_cnt_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_cnt_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_uart_txq_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_was_wd_boot_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_vrefint_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_aio_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ai_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_di_1.04$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_di_1.03$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_di_1.02$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_di_1.01$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nstatus1_rd_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nstatus1_rd_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nstatus1_rd_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.02_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.02_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.02_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.02_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.02_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.02_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_ai_mode1.01_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_ai_mode1.01_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_ai_mode1.01_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_clear_wd_boot_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_wdboot1_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_wdboot1_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_wdboot1_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.04_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.04_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.04_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.01_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.01_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.01_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.02_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.02_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.02_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.03_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.03_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dse1.03_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_reboot_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_reboot1_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_reboot1_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_reboot1_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.04_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.04_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.04_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nao1_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nao1_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nao1_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_ao_mode1.01_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_ao_mode1.01_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_ao_mode1.01_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nmwd_ena1_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nmwd_ena1_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nmwd_ena1_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.02_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.02_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.02_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.03_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.03_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ndo1.03_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_cnt_1.02_set$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.02_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.02_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.02_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nv_save_1$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_save1_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_save1_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nbits_save1_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_cnt_1.04_set$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.04_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.04_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.04_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_cnt_1.03_set$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.03_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.03_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.03_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_uart1.01_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_uart1.01_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_uart1.01_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_cycle1_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_cycle1_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nconfig_cycle1_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_cnt_1.01_set$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.01_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.01_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_ncnt1.01_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.01_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.01_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.01_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.04_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.04_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_npwm1.04_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.03_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.03_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.03_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.02_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.02_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.02_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.04_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.04_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nc_dst1.04_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.04_wr_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.04_wr_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$neuron s10x_nuled1.04_wr_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$1w-thermometer_scratchpad_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$elektromer_l1_apparent_power$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$1w-thermometer_scratchpad_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$1w-thermometer_scratchpad_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$1w-thermometer_convert_commblock$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$1w-thermometer_convert_timestamp$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$1w-thermometer_convert_commerror$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$hw$.$1w-thermometer_temperature$" module="mervis_test_project" />
    <m type="library.metadata.common" fullName="$desired_temperature$" module="mervis_test_project" />
  </values>
</metadata>